- name: Deploy JunitMavenTest
  hosts: onlineStaging
  gather_facts: false
  sudo: yes
  vars_files:
    - '{{varsfile}}.yml'
  pre_tasks:
     - name: mkdir destdir
       file: 
          path: '{{destdir}}'
          state: directory
     - name: Start Files Transfer
       debug: msg="Files Operation Start..."
  
  tasks:
    - name: Delete old testjar
      file:
        path: '{{destdir}}/parameterizedTestsWithRules-1.0.0.jar'
        state: 'absent'

    - name: Start Copy Files
      debug: msg="Copy Start..."
    - name: Copy Front Files
      copy:
        src: '/mnt/DotNetBuilds/{{srcfolder}}/parameterizedTestsWithRules-1.0.0.jar'
        dest: '{{destdir}}'

    - name: CheckResult
      stat:
        path: '{{destdir}}/parameterizedTestsWithRules-1.0.0.jar'
      register:
        sym
      notify:
      - CheckResult

  handlers:
    - name: CheckResult
      debug:
        msg: sym.stat.mtime.stdout_lines